#!/bin/bash

# collect the arguments first, the OpenFOAM environment deletes the arguments
ARGV="$@"
ARGC=$#
for i in $@ 
do 
  shift
done

# now load the OpenFOAM environment
unset FOAM_INST_DIR
source /opt/OpenFOAM/OpenFOAM-6/etc/bashrc &> /dev/null

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${FOAM_LIBBIN}

if [ $ARGC -eq 0 ]
then
  export PROMPT_COMMAND="PS1='of60:\w> '"
  bash $OPT
else
  eval "$ARGV"
fi
